name: CI

on:
  pull_request:
    branches: ["**"]

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/actions/pnpm-setup
      - name: Prettier Check
        run: pnpm -s format:check

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/actions/pnpm-setup
      - name: Lint
        run: pnpm -s lint

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/actions/pnpm-setup
      - name: Test with coverage
        run: pnpm -s test:coverage
